import type { Customer, Order, Product, PromoCode } from "./types";

const now = new Date().toISOString();
const day = (n: number) =>
  new Date(Date.now() - n * 86400000).toISOString();

function shades(
  base: { price: number; prefix: string },
  list: { name: string; hex: string; stock: number }[]
) {
  return list.map((s, i) => ({
    id: `${base.prefix}-v${i + 1}`,
    name: s.name,
    sku: `${base.prefix}-${String(i + 1).padStart(2, "0")}`,
    shadeHex: s.hex,
    price: base.price,
    stock: s.stock,
  }));
}

export function seedProducts(): Product[] {
  return [
    {
      id: "p-veil-foundation",
      slug: "veil-soft-focus-foundation",
      name: "Veil Soft-Focus Foundation",
      tagline: "Weightless coverage. True-to-you finish.",
      description:
        "A breathable, medium-buildable foundation that blurs texture while letting skin live. Formulated across 50 inclusive undertones with skincare actives—hyaluronic spheres, niacinamide, and light-diffusing pigments for an airbrushed glow that lasts 16 hours.",
      category: "makeup",
      subcategory: "Face",
      images: [
        "/images/product-foundation.jpg",
        "/images/hero-model.jpg",
        "/images/texture-abstract.jpg",
      ],
      price: 42,
      rating: 4.8,
      reviewCount: 2840,
      badges: ["bestseller", "new"],
      shades: 50,
      featured: true,
      active: true,
      ingredients: [
        "Hyaluronic Acid",
        "Niacinamide",
        "Squalane",
        "Light-Diffusing Mica",
      ],
      howToUse:
        "Dispense a pump, warm between fingers, and press into skin from center outward. Build where needed.",
      variants: shades(
        { price: 42, prefix: "LM-VEIL" },
        [
          { name: "Porcelain 01C", hex: "#F5E6D8", stock: 42 },
          { name: "Ivory 05N", hex: "#EED9C4", stock: 38 },
          { name: "Sand 12W", hex: "#E0C3A8", stock: 55 },
          { name: "Honey 18N", hex: "#C99B72", stock: 61 },
          { name: "Amber 24W", hex: "#A8704A", stock: 48 },
          { name: "Cocoa 32N", hex: "#7A4A32", stock: 44 },
          { name: "Espresso 40C", hex: "#4A2C1E", stock: 36 },
          { name: "Obsidian 48N", hex: "#2E1A12", stock: 29 },
        ]
      ),
      createdAt: day(40),
      updatedAt: now,
    },
    {
      id: "p-lume-gloss",
      slug: "lume-glass-lip-oil",
      name: "Lumé Glass Lip Oil",
      tagline: "Mirror shine. Cushion comfort.",
      description:
        "A non-sticky lip oil that floods lips with high-refraction gloss and nourishing botanicals. One swipe delivers dimensional color and a glass-skin finish that feels like a serum, looks like light.",
      category: "makeup",
      subcategory: "Lips",
      images: [
        "/images/product-gloss.jpg",
        "/images/texture-abstract.jpg",
        "/images/hero-model.jpg",
      ],
      price: 24,
      rating: 4.9,
      reviewCount: 5120,
      badges: ["bestseller", "viral"],
      shades: 18,
      featured: true,
      active: true,
      ingredients: ["Jojoba Oil", "Vitamin E", "Peptide Complex", "Mica"],
      howToUse: "Glide once for sheer glass, twice for saturated shine.",
      variants: shades(
        { price: 24, prefix: "LM-GLASS" },
        [
          { name: "Nude Prism", hex: "#E8C4B8", stock: 72 },
          { name: "Rose Quartz", hex: "#E8A0A8", stock: 88 },
          { name: "Coral Signal", hex: "#E87868", stock: 64 },
          { name: "Berry Circuit", hex: "#A83858", stock: 51 },
          { name: "Cherry Static", hex: "#C82838", stock: 47 },
          { name: "Clear Aura", hex: "#F5EDE8", stock: 120 },
        ]
      ),
      createdAt: day(60),
      updatedAt: now,
    },
    {
      id: "p-aura-serum",
      slug: "aura-illuminating-serum",
      name: "Aura Illuminating Serum",
      tagline: "Light from within. Clinically calm.",
      description:
        "A featherweight illuminating serum that primes, hydrates, and refracts light. 5% niacinamide, fermented rice water, and micro-pearls deliver glass-skin radiance without glitter or grease.",
      category: "skin",
      subcategory: "Treat",
      images: [
        "/images/skincare-still.jpg",
        "/images/texture-abstract.jpg",
        "/images/hero-model.jpg",
      ],
      price: 58,
      rating: 4.7,
      reviewCount: 1960,
      badges: ["bestseller"],
      sizes: ["30ml", "50ml"],
      featured: true,
      active: true,
      ingredients: [
        "5% Niacinamide",
        "Fermented Rice Water",
        "Micro-Pearl Complex",
        "Centella",
      ],
      howToUse:
        "After cleansing, press 3–4 drops onto damp skin morning and night. Layer under Veil foundation.",
      variants: [
        {
          id: "aura-30",
          name: "30ml",
          sku: "LM-AURA-30",
          price: 58,
          stock: 140,
        },
        {
          id: "aura-50",
          name: "50ml",
          sku: "LM-AURA-50",
          price: 88,
          stock: 76,
        },
      ],
      createdAt: day(90),
      updatedAt: now,
    },
    {
      id: "p-silk-body",
      slug: "silk-veil-body-creme",
      name: "Silk Veil Body Crème",
      tagline: "Buttery melt. Second-skin soft.",
      description:
        "A whipped oil-crème that melts into skin with shea, marula, and a signature soft-musk scent. Leaves a luminous, non-greasy veil—the body equivalent of glass skin.",
      category: "body",
      subcategory: "Moisturize",
      images: [
        "/images/product-bodycream.jpg",
        "/images/skincare-still.jpg",
        "/images/texture-abstract.jpg",
      ],
      price: 36,
      rating: 4.8,
      reviewCount: 3210,
      badges: ["new", "bestseller"],
      shades: 4,
      featured: true,
      active: true,
      ingredients: ["Shea Butter", "Marula Oil", "Squalane", "Vitamin B5"],
      howToUse: "Massage onto clean skin after bathing while still damp.",
      variants: shades(
        { price: 36, prefix: "LM-SILK" },
        [
          { name: "Vanilla Musk", hex: "#F5E6D0", stock: 95 },
          { name: "Fig & Cashmere", hex: "#E8D4C8", stock: 68 },
          { name: "Citrus Bloom", hex: "#F0E8C8", stock: 52 },
          { name: "Sandalwood Milk", hex: "#D8C8B0", stock: 41 },
        ]
      ),
      createdAt: day(20),
      updatedAt: now,
    },
    {
      id: "p-sun-sculpt",
      slug: "sun-sculpt-creme-bronzer",
      name: "Sun Sculpt Crème Bronzer",
      tagline: "Warmth, not weight.",
      description:
        "A mousse-crème bronzer that melts into skin for a lived-in sunlit flush. Buildable, blendable, never muddy—across 10 undertone-true shades.",
      category: "makeup",
      subcategory: "Face",
      images: [
        "/images/product-bronzer.jpg",
        "/images/hero-model.jpg",
        "/images/texture-abstract.jpg",
      ],
      price: 34,
      rating: 4.7,
      reviewCount: 1540,
      badges: ["new"],
      shades: 10,
      featured: true,
      active: true,
      ingredients: ["Jojoba Esters", "Vitamin E", "Iron Oxides"],
      howToUse: "Sweep along high planes of face where sun would naturally hit.",
      variants: shades(
        { price: 34, prefix: "LM-SUN" },
        [
          { name: "Soft Solstice", hex: "#D4A888", stock: 58 },
          { name: "Maple Light", hex: "#C48858", stock: 72 },
          { name: "Terra Glow", hex: "#A86840", stock: 45 },
          { name: "Deep Ember", hex: "#7A4828", stock: 38 },
        ]
      ),
      createdAt: day(15),
      updatedAt: now,
    },
    {
      id: "p-flux-oil",
      slug: "flux-9-in-1-hair-oil",
      name: "Flux 9-in-1 Hair Oil",
      tagline: "One drop. Full spectrum repair.",
      description:
        "A weightless multi-oil elixir for heat protection, shine, frizz control, split-end sealing, and scalp calm. Works on every texture—coils to pin-straight.",
      category: "hair",
      subcategory: "Treat",
      images: [
        "/images/product-hairoil.jpg",
        "/images/texture-abstract.jpg",
        "/images/hero-model.jpg",
      ],
      price: 32,
      rating: 4.6,
      reviewCount: 980,
      badges: ["new", "viral"],
      featured: true,
      active: true,
      ingredients: [
        "Argan Oil",
        "Camellia Seed",
        "Squalane",
        "Heat Shield Polymer",
      ],
      howToUse:
        "1–3 drops on mid-lengths to ends, damp or dry. Use sparingly on fine hair.",
      variants: [
        {
          id: "flux-default",
          name: "50ml",
          sku: "LM-FLUX-50",
          price: 32,
          stock: 110,
        },
      ],
      createdAt: day(12),
      updatedAt: now,
    },
    {
      id: "p-clean-canvas",
      slug: "clean-canvas-gel-cleanser",
      name: "Clean Canvas Gel Cleanser",
      tagline: "Remove everything. Disturb nothing.",
      description:
        "A pH-balanced gel cleanser that melts makeup and SPF without stripping the barrier. Amino-acid surfactants leave skin soft, calm, and ready for Aura.",
      category: "skin",
      subcategory: "Cleanse",
      images: [
        "/images/skincare-still.jpg",
        "/images/product-foundation.jpg",
      ],
      price: 28,
      compareAtPrice: 32,
      rating: 4.7,
      reviewCount: 2210,
      badges: ["bestseller"],
      sizes: ["100ml", "200ml"],
      featured: false,
      active: true,
      ingredients: ["Amino Acid Surfactants", "Panthenol", "Aloe", "Glycerin"],
      howToUse: "Massage onto damp face, rinse with lukewarm water. AM/PM.",
      variants: [
        {
          id: "clean-100",
          name: "100ml",
          sku: "LM-CLEAN-100",
          price: 28,
          stock: 160,
        },
        {
          id: "clean-200",
          name: "200ml",
          sku: "LM-CLEAN-200",
          price: 42,
          stock: 90,
        },
      ],
      createdAt: day(100),
      updatedAt: now,
    },
    {
      id: "p-tint-balm",
      slug: "tint-balm-moisture-barrier",
      name: "Tint Balm Moisture Barrier",
      tagline: "Care first. Color second.",
      description:
        "A ceramide-rich tinted balm that rebuilds the lip barrier while delivering a soft wash of color. SPF 15. Zero stickiness.",
      category: "makeup",
      subcategory: "Lips",
      images: [
        "/images/product-gloss.jpg",
        "/images/product-bodycream.jpg",
      ],
      price: 18,
      rating: 4.5,
      reviewCount: 870,
      badges: ["new"],
      shades: 8,
      featured: false,
      active: true,
      ingredients: ["Ceramides", "Shea", "SPF 15", "Peptides"],
      howToUse: "Apply liberally as needed throughout the day.",
      variants: shades(
        { price: 18, prefix: "LM-TINT" },
        [
          { name: "Bare", hex: "#E8D0C4", stock: 80 },
          { name: "Blush", hex: "#E8A8A0", stock: 65 },
          { name: "Mauve", hex: "#C88898", stock: 54 },
          { name: "Spice", hex: "#B87060", stock: 48 },
        ]
      ),
      createdAt: day(8),
      updatedAt: now,
    },
    {
      id: "p-starter-set",
      slug: "lumea-ritual-starter-set",
      name: "Luméa Ritual Starter Set",
      tagline: "Cleanse. Illuminate. Veil.",
      description:
        "Travel-ready trio: Clean Canvas cleanser, Aura serum mini, and a deluxe Veil foundation sample in your shade. The complete morning ritual.",
      category: "sets",
      subcategory: "Kits",
      images: [
        "/images/skincare-still.jpg",
        "/images/hero-products.jpg",
        "/images/product-foundation.jpg",
      ],
      price: 48,
      compareAtPrice: 72,
      rating: 4.9,
      reviewCount: 640,
      badges: ["bestseller", "limited"],
      featured: true,
      active: true,
      howToUse: "Follow AM ritual: cleanse → serum → foundation.",
      variants: [
        {
          id: "set-ritual",
          name: "Ritual Trio",
          sku: "LM-SET-RITUAL",
          price: 48,
          compareAtPrice: 72,
          stock: 35,
        },
      ],
      createdAt: day(5),
      updatedAt: now,
    },
    {
      id: "p-night-mask",
      slug: "night-restore-sleeping-mask",
      name: "Night Restore Sleeping Mask",
      tagline: "Wake up glass.",
      description:
        "An overnight recovery mask with bakuchiol, peptides, and ceramide complex. Plumps fine lines and restores barrier while you sleep.",
      category: "skin",
      subcategory: "Night",
      images: [
        "/images/product-bodycream.jpg",
        "/images/skincare-still.jpg",
      ],
      price: 52,
      rating: 4.6,
      reviewCount: 720,
      badges: ["coming-soon"],
      featured: false,
      active: true,
      ingredients: ["Bakuchiol", "Peptide Complex", "Ceramides", "Squalane"],
      howToUse: "Apply a thin layer as last PM step. Rinse in the morning optional.",
      variants: [
        {
          id: "night-50",
          name: "50ml",
          sku: "LM-NIGHT-50",
          price: 52,
          stock: 0,
        },
      ],
      createdAt: day(2),
      updatedAt: now,
    },
    // ── Contour / makeup expand ──────────────────────────
    {
      id: "p-contour-sculpt",
      slug: "edge-sculpt-contour-palette",
      name: "Edge Sculpt Contour Palette",
      tagline: "Bone structure, soft-focus.",
      description:
        "Four melt-in powders for cheek hollows, jaw, nose, and highlight. Buildable, never chalky — mapped for every undertone in the Virtual Studio.",
      category: "makeup",
      subcategory: "Face",
      images: [
        "/images/product-contour.jpg",
        "/images/product-bronzer.jpg",
        "/images/studio-white.jpg",
      ],
      price: 46,
      rating: 4.8,
      reviewCount: 1120,
      badges: ["new", "viral"],
      shades: 4,
      featured: true,
      active: true,
      howToUse:
        "Sweep cooler tones under cheekbones, warmer through hollows. Blend in circular motions. Try in Mirror Studio first.",
      variants: shades(
        { price: 46, prefix: "LM-EDGE" },
        [
          { name: "Fair Sculpt", hex: "#E0C4A8", stock: 48 },
          { name: "Medium Carve", hex: "#C49870", stock: 62 },
          { name: "Deep Define", hex: "#8A5A3A", stock: 40 },
          { name: "Rich Structure", hex: "#5A3824", stock: 34 },
        ]
      ),
      createdAt: day(3),
      updatedAt: now,
    },
    // ── Hair ─────────────────────────────────────────────
    {
      id: "p-clean-shine-shampoo",
      slug: "clean-shine-balancing-shampoo",
      name: "Clean Shine Balancing Shampoo",
      tagline: "Clarify without the crash.",
      description:
        "A sulfate-free cleanse that lifts buildup while preserving natural oils. Works on fine, coily, colour-treated, and textured hair.",
      category: "hair",
      subcategory: "Cleanse",
      images: ["/images/product-haircare.jpg", "/images/product-hairoil.jpg"],
      price: 28,
      rating: 4.6,
      reviewCount: 890,
      badges: ["new", "bestseller"],
      sizes: ["250ml", "500ml"],
      featured: true,
      active: true,
      ingredients: ["Amino surfactants", "Rice protein", "Panthenol"],
      howToUse: "Massage into wet scalp, rinse. Follow with Conditioner or Mask.",
      variants: [
        { id: "sh-250", name: "250ml", sku: "LM-SH-250", price: 28, stock: 120 },
        { id: "sh-500", name: "500ml", sku: "LM-SH-500", price: 42, stock: 70 },
      ],
      createdAt: day(11),
      updatedAt: now,
    },
    {
      id: "p-silk-conditioner",
      slug: "silk-slip-conditioner",
      name: "Silk Slip Conditioner",
      tagline: "Detangle. Soften. Reflect.",
      description:
        "Weightless slip for effortless comb-through and mirror shine. Heat-protect polymers included.",
      category: "hair",
      subcategory: "Condition",
      images: ["/images/product-haircare.jpg", "/images/texture-abstract.jpg"],
      price: 30,
      rating: 4.7,
      reviewCount: 760,
      badges: ["bestseller"],
      sizes: ["250ml", "500ml"],
      featured: false,
      active: true,
      ingredients: ["Squalane", "Silk amino acids", "Heat shield"],
      howToUse: "Apply mid-lengths to ends, leave 1–2 min, rinse.",
      variants: [
        { id: "cd-250", name: "250ml", sku: "LM-CD-250", price: 30, stock: 110 },
        { id: "cd-500", name: "500ml", sku: "LM-CD-500", price: 46, stock: 55 },
      ],
      createdAt: day(11),
      updatedAt: now,
    },
    {
      id: "p-hair-mask",
      slug: "repair-cloud-hair-mask",
      name: "Repair Cloud Hair Mask",
      tagline: "Weekly rescue. Daily soft.",
      description:
        "A whipped bond-repair mask that rebuilds strength after heat, colour, and braids. 5-minute or overnight.",
      category: "hair",
      subcategory: "Treat",
      images: ["/images/product-hairmask.jpg", "/images/product-hairoil.jpg"],
      price: 38,
      rating: 4.8,
      reviewCount: 540,
      badges: ["new", "viral"],
      featured: true,
      active: true,
      ingredients: ["Bond complex", "Shea", "Ceramide"],
      howToUse: "Apply to clean damp hair, leave 5–20 min or overnight under a wrap.",
      variants: [
        { id: "hm-200", name: "200ml", sku: "LM-HM-200", price: 38, stock: 85 },
      ],
      createdAt: day(6),
      updatedAt: now,
    },
    {
      id: "p-dry-shampoo",
      slug: "air-lift-dry-shampoo",
      name: "Air Lift Dry Shampoo",
      tagline: "Invisible volume. Zero cast.",
      description:
        "A translucent dry shampoo powder mist that absorbs oil and lifts roots without white residue — across dark and light hair.",
      category: "hair",
      subcategory: "Style",
      images: ["/images/product-dryshampoo.jpg", "/images/product-haircare.jpg"],
      price: 26,
      rating: 4.5,
      reviewCount: 1320,
      badges: ["bestseller"],
      featured: false,
      active: true,
      ingredients: ["Rice starch", "Silica", "Fragrance-free option"],
      howToUse: "Shake, spray at roots from 20cm, massage, brush through.",
      variants: [
        { id: "ds-default", name: "150ml", sku: "LM-DS-150", price: 26, stock: 140 },
      ],
      createdAt: day(18),
      updatedAt: now,
    },
    {
      id: "p-curl-cream",
      slug: "coil-define-curl-cream",
      name: "Coil Define Curl Cream",
      tagline: "Definition without crunch.",
      description:
        "A soft-hold cream for waves to 4C coils. Reduces frizz, enhances pattern, never sticky.",
      category: "hair",
      subcategory: "Style",
      images: ["/images/product-hairmask.jpg", "/images/product-hairoil.jpg"],
      price: 32,
      rating: 4.7,
      reviewCount: 680,
      badges: ["new"],
      featured: true,
      active: true,
      ingredients: ["Flaxseed", "Jojoba", "Glycerin"],
      howToUse: "Rake through damp hair, scrunch or coil, air-dry or diffuse.",
      variants: [
        { id: "cc-default", name: "200ml", sku: "LM-CC-200", price: 32, stock: 95 },
      ],
      createdAt: day(9),
      updatedAt: now,
    },
    // ── Body ─────────────────────────────────────────────
    {
      id: "p-body-oil",
      slug: "lumen-dry-body-oil",
      name: "Lumen Dry Body Oil",
      tagline: "Liquid light for skin.",
      description:
        "A fast-absorbing dry oil with shimmer option and non-shimmer. Soft musk and citrus. Ideal post-shower glow.",
      category: "body",
      subcategory: "Oil",
      images: ["/images/product-bodyoil.jpg", "/images/product-bodycream.jpg"],
      price: 40,
      rating: 4.8,
      reviewCount: 910,
      badges: ["bestseller", "new"],
      featured: true,
      active: true,
      ingredients: ["Marula", "Squalane", "Vitamin E"],
      howToUse: "Press onto damp skin. Face-safe on cheeks for glow.",
      variants: [
        { id: "bo-clear", name: "Clear Glow 100ml", sku: "LM-BO-CL", price: 40, stock: 70 },
        { id: "bo-shimmer", name: "Soft Shimmer 100ml", sku: "LM-BO-SH", price: 42, stock: 55 },
      ],
      createdAt: day(7),
      updatedAt: now,
    },
    {
      id: "p-body-scrub",
      slug: "polish-sugar-body-scrub",
      name: "Polish Sugar Body Scrub",
      tagline: "Smooth canvas. Soft scent.",
      description:
        "Fine sugar and jojoba beads polish without micro-tears. Leaves a veil of moisture — no tight after-feel.",
      category: "body",
      subcategory: "Exfoliate",
      images: ["/images/product-bodycream.jpg", "/images/product-bodyoil.jpg"],
      price: 34,
      rating: 4.6,
      reviewCount: 520,
      badges: ["new"],
      featured: false,
      active: true,
      ingredients: ["Cane sugar", "Jojoba beads", "Shea"],
      howToUse: "Massage on wet skin in shower, rinse. 2–3× weekly.",
      variants: [
        { id: "bs-vanilla", name: "Vanilla Silk", sku: "LM-BS-VN", price: 34, stock: 60 },
        { id: "bs-citrus", name: "Citrus Fresh", sku: "LM-BS-CT", price: 34, stock: 48 },
      ],
      createdAt: day(14),
      updatedAt: now,
    },
    {
      id: "p-hand-cream",
      slug: "velvet-hand-creme",
      name: "Velvet Hand Crème",
      tagline: "Pocket luxury. Instant soft.",
      description:
        "A non-greasy hand crème with ceramides and soft powder finish. Fits in every bag.",
      category: "body",
      subcategory: "Hands",
      images: ["/images/product-bodycream.jpg", "/images/skincare-still.jpg"],
      price: 18,
      rating: 4.7,
      reviewCount: 430,
      badges: ["bestseller"],
      featured: false,
      active: true,
      ingredients: ["Ceramides", "Shea", "Allantoin"],
      howToUse: "Apply after washing hands and at night.",
      variants: [
        { id: "hc-50", name: "50ml", sku: "LM-HC-50", price: 18, stock: 200 },
      ],
      createdAt: day(30),
      updatedAt: now,
    },
    // ── Tools ────────────────────────────────────────────
    {
      id: "p-brush-set",
      slug: "atelier-essential-brush-set",
      name: "Atelier Essential Brush Set",
      tagline: "Six brushes. Every face.",
      description:
        "Vegan bristles, champagne ferrules, balanced handles. Face, eye, lip, and contour brushes engineered for Mirror Studio techniques.",
      category: "tools",
      subcategory: "Brushes",
      images: ["/images/product-brushes.jpg", "/images/studio-white.jpg"],
      price: 68,
      compareAtPrice: 92,
      rating: 4.9,
      reviewCount: 780,
      badges: ["bestseller", "limited"],
      featured: true,
      active: true,
      howToUse: "Use dry for powder, damp for cream. Clean weekly.",
      variants: [
        { id: "br-set", name: "6-Piece Set", sku: "LM-BR-SET6", price: 68, stock: 45 },
      ],
      createdAt: day(4),
      updatedAt: now,
    },
    {
      id: "p-contour-brush",
      slug: "sculpt-angle-contour-brush",
      name: "Sculpt Angle Contour Brush",
      tagline: "Precision hollows.",
      description:
        "Angled dual-density brush for seamless contour and bronzer placement — mirrors artist techniques in Tutorials.",
      category: "tools",
      subcategory: "Brushes",
      images: ["/images/product-brushes.jpg", "/images/product-contour.jpg"],
      price: 28,
      rating: 4.8,
      reviewCount: 390,
      badges: ["new"],
      featured: false,
      active: true,
      howToUse: "Sweep under cheekbone from ear toward mouth, blend upward.",
      variants: [
        { id: "br-contour", name: "Single", sku: "LM-BR-CT", price: 28, stock: 90 },
      ],
      createdAt: day(4),
      updatedAt: now,
    },
    {
      id: "p-sponge",
      slug: "cloud-bounce-beauty-sponge",
      name: "Cloud Bounce Beauty Sponge",
      tagline: "Zero streak. Max bounce.",
      description:
        "Latex-free sponge that expands in water for airbrushed foundation and concealer. Includes travel case.",
      category: "tools",
      subcategory: "Applicators",
      images: ["/images/product-sponge.jpg", "/images/product-foundation.jpg"],
      price: 16,
      rating: 4.7,
      reviewCount: 2100,
      badges: ["bestseller", "viral"],
      featured: true,
      active: true,
      howToUse: "Wet, squeeze, bounce product into skin. Replace every 1–2 months.",
      variants: [
        { id: "sp-peach", name: "Peach", sku: "LM-SP-PCH", price: 16, stock: 180 },
        { id: "sp-lilac", name: "Lilac", sku: "LM-SP-LIL", price: 16, stock: 120 },
      ],
      createdAt: day(20),
      updatedAt: now,
    },
    {
      id: "p-lash-curler",
      slug: "lift-frame-lash-curler",
      name: "Lift Frame Lash Curler",
      tagline: "Root lift that lasts.",
      description:
        "Ergonomic curler with soft silicone pad for every eye shape. No pinch design.",
      category: "tools",
      subcategory: "Eyes",
      images: ["/images/product-brushes.jpg", "/images/hero-model.jpg"],
      price: 22,
      rating: 4.6,
      reviewCount: 560,
      badges: ["new"],
      featured: false,
      active: true,
      howToUse: "Curl at root, mid, tip before mascara. Warm pad slightly for more hold.",
      variants: [
        { id: "lc-default", name: "Standard", sku: "LM-LC-01", price: 22, stock: 100 },
      ],
      createdAt: day(16),
      updatedAt: now,
    },
    {
      id: "p-brush-cleaner",
      slug: "pure-reset-brush-cleaner",
      name: "Pure Reset Brush Cleaner",
      tagline: "Clean tools, true colour.",
      description:
        "Fast-dry spray and deep-clean liquid duo that protects bristles and removes pigment residue.",
      category: "tools",
      subcategory: "Care",
      images: ["/images/product-sponge.jpg", "/images/product-brushes.jpg"],
      price: 20,
      rating: 4.5,
      reviewCount: 310,
      badges: [],
      featured: false,
      active: true,
      howToUse: "Spray for quick cleanse between looks; liquid for weekly deep clean.",
      variants: [
        { id: "bc-duo", name: "Spray + Liquid", sku: "LM-BC-DUO", price: 20, stock: 75 },
      ],
      createdAt: day(22),
      updatedAt: now,
    },
    // ── Sets ─────────────────────────────────────────────
    {
      id: "p-glow-edit-set",
      slug: "glow-edit-full-face-set",
      name: "Glow Edit Full Face Set",
      tagline: "Foundation · Contour · Gloss · Sponge",
      description:
        "The conversion kit: Veil mini, Edge contour duo, Lumé Glass, Cloud sponge. Built for play-before-you-buy in Mirror Studio.",
      category: "sets",
      subcategory: "Kits",
      images: [
        "/images/product-giftset.jpg",
        "/images/product-foundation.jpg",
        "/images/product-contour.jpg",
      ],
      price: 98,
      compareAtPrice: 128,
      rating: 4.9,
      reviewCount: 420,
      badges: ["limited", "bestseller"],
      featured: true,
      active: true,
      howToUse: "Try each shade in studio, then apply with sponge and brushes.",
      variants: [
        { id: "set-glow", name: "Full Edit", sku: "LM-SET-GLOW", price: 98, stock: 28 },
      ],
      createdAt: day(1),
      updatedAt: now,
    },
    {
      id: "p-hair-ritual-set",
      slug: "hair-ritual-cleanse-treat-set",
      name: "Hair Ritual Cleanse + Treat Set",
      tagline: "Shampoo · Conditioner · Oil · Mask mini",
      description:
        "Complete hair house ritual for all textures. Clean Shine, Silk Slip, Flux oil mini, Repair Cloud sachet.",
      category: "sets",
      subcategory: "Hair kits",
      images: [
        "/images/product-giftset.jpg",
        "/images/product-haircare.jpg",
        "/images/product-hairoil.jpg",
      ],
      price: 88,
      compareAtPrice: 118,
      rating: 4.8,
      reviewCount: 290,
      badges: ["new", "limited"],
      featured: true,
      active: true,
      howToUse: "Cleanse → condition → weekly mask → oil on ends.",
      variants: [
        { id: "set-hair", name: "Ritual Box", sku: "LM-SET-HAIR", price: 88, stock: 32 },
      ],
      createdAt: day(2),
      updatedAt: now,
    },
    {
      id: "p-body-spa-set",
      slug: "body-spa-soft-set",
      name: "Body Spa Soft Set",
      tagline: "Scrub · Crème · Oil",
      description:
        "Polish Sugar scrub, Silk Veil body crème, Lumen dry oil — the at-home spa trio.",
      category: "sets",
      subcategory: "Body kits",
      images: [
        "/images/product-giftset.jpg",
        "/images/product-bodycream.jpg",
        "/images/product-bodyoil.jpg",
      ],
      price: 92,
      compareAtPrice: 110,
      rating: 4.7,
      reviewCount: 210,
      badges: ["new"],
      featured: false,
      active: true,
      howToUse: "Scrub in shower → oil on damp skin → crème on dry areas.",
      variants: [
        { id: "set-body", name: "Spa Trio", sku: "LM-SET-BODY", price: 92, stock: 40 },
      ],
      createdAt: day(3),
      updatedAt: now,
    },
    {
      id: "p-tool-pro-set",
      slug: "pro-tool-starter-kit",
      name: "Pro Tool Starter Kit",
      tagline: "Brushes · Sponge · Cleaner · Curler",
      description:
        "Everything to apply like a pro at home: Atelier brush trio, Cloud sponge, Pure Reset, Lift Frame curler.",
      category: "sets",
      subcategory: "Tool kits",
      images: [
        "/images/product-brushes.jpg",
        "/images/product-sponge.jpg",
        "/images/studio-white.jpg",
      ],
      price: 79,
      compareAtPrice: 102,
      rating: 4.8,
      reviewCount: 350,
      badges: ["bestseller"],
      featured: true,
      active: true,
      howToUse: "Pair with Tutorials and Mirror Studio for technique practice.",
      variants: [
        { id: "set-tools", name: "Pro Kit", sku: "LM-SET-TOOLS", price: 79, stock: 38 },
      ],
      createdAt: day(4),
      updatedAt: now,
    },
  ];
}

export function seedCustomers(): Customer[] {
  return [
    {
      id: "c-001",
      email: "maya.chen@email.com",
      firstName: "Maya",
      lastName: "Chen",
      phone: "+1 415 555 0142",
      addresses: [
        {
          firstName: "Maya",
          lastName: "Chen",
          line1: "128 Market St",
          city: "San Francisco",
          state: "CA",
          postalCode: "94105",
          country: "US",
          phone: "+1 415 555 0142",
        },
      ],
      totalOrders: 4,
      totalSpent: 286,
      tags: ["vip", "shade-matching"],
      createdAt: day(45),
      updatedAt: day(3),
    },
    {
      id: "c-002",
      email: "jordan.okonkwo@email.com",
      firstName: "Jordan",
      lastName: "Okonkwo",
      phone: "+1 212 555 0198",
      addresses: [
        {
          firstName: "Jordan",
          lastName: "Okonkwo",
          line1: "90 Bedford Ave",
          city: "Brooklyn",
          state: "NY",
          postalCode: "11211",
          country: "US",
        },
      ],
      totalOrders: 2,
      totalSpent: 124,
      tags: ["newsletter"],
      createdAt: day(20),
      updatedAt: day(7),
    },
    {
      id: "c-003",
      email: "sofia.reyes@email.com",
      firstName: "Sofia",
      lastName: "Reyes",
      addresses: [
        {
          firstName: "Sofia",
          lastName: "Reyes",
          line1: "4400 N Central Expy",
          city: "Dallas",
          state: "TX",
          postalCode: "75206",
          country: "US",
        },
      ],
      totalOrders: 1,
      totalSpent: 48,
      tags: ["new"],
      createdAt: day(4),
      updatedAt: day(4),
    },
  ];
}

export function seedOrders(): Order[] {
  return [
    {
      id: "o-001",
      orderNumber: "LM10028401",
      customerId: "c-001",
      email: "maya.chen@email.com",
      status: "shipped",
      fulfillmentStatus: "fulfilled",
      items: [
        {
          productId: "p-veil-foundation",
          variantId: "LM-VEIL-v4",
          name: "Veil Soft-Focus Foundation",
          variantName: "Honey 18N",
          sku: "LM-VEIL-04",
          quantity: 1,
          unitPrice: 42,
          image: "/images/product-foundation.jpg",
        },
        {
          productId: "p-lume-gloss",
          variantId: "LM-GLASS-v2",
          name: "Lumé Glass Lip Oil",
          variantName: "Rose Quartz",
          sku: "LM-GLASS-02",
          quantity: 2,
          unitPrice: 24,
          image: "/images/product-gloss.jpg",
        },
      ],
      subtotal: 90,
      shipping: 0,
      tax: 7.2,
      discount: 0,
      total: 97.2,
      currency: "USD",
      shippingAddress: {
        firstName: "Maya",
        lastName: "Chen",
        line1: "128 Market St",
        city: "San Francisco",
        state: "CA",
        postalCode: "94105",
        country: "US",
      },
      trackingNumber: "1Z999AA10123456784",
      createdAt: day(3),
      updatedAt: day(2),
      fulfilledAt: day(2),
    },
    {
      id: "o-002",
      orderNumber: "LM10028412",
      customerId: "c-002",
      email: "jordan.okonkwo@email.com",
      status: "processing",
      fulfillmentStatus: "unfulfilled",
      items: [
        {
          productId: "p-flux-oil",
          variantId: "flux-default",
          name: "Flux 9-in-1 Hair Oil",
          variantName: "50ml",
          sku: "LM-FLUX-50",
          quantity: 1,
          unitPrice: 32,
          image: "/images/product-hairoil.jpg",
        },
        {
          productId: "p-silk-body",
          variantId: "LM-SILK-v1",
          name: "Silk Veil Body Crème",
          variantName: "Vanilla Musk",
          sku: "LM-SILK-01",
          quantity: 1,
          unitPrice: 36,
          image: "/images/product-bodycream.jpg",
        },
      ],
      subtotal: 68,
      shipping: 8,
      tax: 6.08,
      discount: 0,
      total: 82.08,
      currency: "USD",
      shippingAddress: {
        firstName: "Jordan",
        lastName: "Okonkwo",
        line1: "90 Bedford Ave",
        city: "Brooklyn",
        state: "NY",
        postalCode: "11211",
        country: "US",
      },
      createdAt: day(1),
      updatedAt: day(1),
    },
    {
      id: "o-003",
      orderNumber: "LM10028420",
      customerId: "c-003",
      email: "sofia.reyes@email.com",
      status: "paid",
      fulfillmentStatus: "unfulfilled",
      items: [
        {
          productId: "p-starter-set",
          variantId: "set-ritual",
          name: "Luméa Ritual Starter Set",
          variantName: "Ritual Trio",
          sku: "LM-SET-RITUAL",
          quantity: 1,
          unitPrice: 48,
          image: "/images/skincare-still.jpg",
        },
      ],
      subtotal: 48,
      shipping: 8,
      tax: 4.48,
      discount: 0,
      total: 60.48,
      currency: "USD",
      shippingAddress: {
        firstName: "Sofia",
        lastName: "Reyes",
        line1: "4400 N Central Expy",
        city: "Dallas",
        state: "TX",
        postalCode: "75206",
        country: "US",
      },
      createdAt: day(0),
      updatedAt: day(0),
    },
  ];
}

export function seedPromos(): PromoCode[] {
  return [
    { code: "LUME15", type: "percent", value: 15, minSubtotal: 50, active: true },
    { code: "LUME25", type: "percent", value: 25, minSubtotal: 75, active: true },
    { code: "WELCOME10", type: "fixed", value: 10, active: true },
    { code: "NYMA15", type: "percent", value: 15, minSubtotal: 40, active: true },
    { code: "COILS20", type: "percent", value: 20, minSubtotal: 55, active: true },
    { code: "GLASS10", type: "fixed", value: 10, minSubtotal: 30, active: true },
    { code: "ICON25", type: "percent", value: 25, minSubtotal: 100, active: true },
    { code: "WARMTH15", type: "percent", value: 15, minSubtotal: 45, active: true },
  ];
}
